In [10]:
from optinum import base_ops

In [11]:
?? base_ops

Type:        module
String form: <module 'optinum.base_ops' from '/Users/vladimir/Documents/VS_Code/Num_analysis/part 2/exam/optinum/optinum/base_ops.py'>
File:        ~/Documents/VS_Code/Num_analysis/part 2/exam/optinum/optinum/base_ops.py
Source:     
from typing import List

def add(matrix_a: List[List], matrix_b: List[List]) -> List[List]:
    """
    Складывает две матрицы одинакового размера.
    
    :param matrix_a: Первая матрица
    :param matrix_b: Вторая матрица
    :return: Результирующая матрица, представляющая собой сумму matrix_a и matrix_b
    """
    return [[matrix_a[i][j] + matrix_b[i][j] for j in range(len(matrix_a[0]))] for i in range(len(matrix_a))]

def subtract(matrix_a: List[List], matrix_b: List[List]) -> List[List]:
    """
    Вычитает одну матрицу из другой матрицы одинакового размера.
    
    :param matrix_a: Первая матрица
    :param matrix_b: Вторая матрица
    :return: Результирующая матрица, представляющая собой разность matrix_a и matrix_b
    """
 

In [12]:
from optinum.base_ops import strassen_multiply

In [13]:
A = [[1, 2], [3, 4]]
B = [[5, 6], [7, 8]]

strassen_multiply(A, B)

[[19, 22], [43, 50]]

In [14]:
import numpy as np
np.dot(A, B) # same as strassen_multiply(A, B)

array([[19, 22],
       [43, 50]])

In [15]:
from optinum.signal import dft, idft

In [16]:
a = [1, 2, 3, 4]
dft(a).round(2)

array([10.+0.j, -2.+2.j, -2.-0.j, -2.-2.j])

In [17]:
idft(dft(a)).round(2)

array([1.-0.j, 2.-0.j, 3.-0.j, 4.+0.j])

In [18]:
?? dft

Signature:  dft(x: numpy.ndarray[numpy.complex128]) -> numpy.ndarray[numpy.complex128]
Source:   
def dft(x: np.ndarray[np.complex128]) -> np.ndarray[np.complex128]:
    """
    Вычисляет дискретное преобразование Фурье (ДПФ) входного сигнала.

    Функция реализует ДПФ, используя матричное умножение для эффективного вычисления.

    Параметры
    ----------
    x : np.ndarray[np.complex128]
        Входной сигнал как массив комплексных чисел

    Возвращает
    ----------
    np.ndarray[np.complex128]
        Результат ДПФ - массив комплексных чисел той же длины, что и входной сигнал

    Пример
    -------
    >>> x = np.array([1+0j, 2+0j, 3+0j, 4+0j])
    >>> dft(x)
    array([ 10.+0.j,  -2.+2.j,  -2.+0.j,  -2.-2.j])
    """
    N = len(x)
    n = np.arange(N)[:, None]  # Create a column vector of n
    k = np.arange(N)[None, :]  # Create a row vector of k
    W = np.exp(-2j * np.pi * k * n / N)  # Calculate the DFT matrix using broadcasting
    return x @ W
File:      ~/Documents/V

In [19]:
from optinum.signal import fft, ifft

In [20]:
fft(a).round(2)

array([10.+0.j, -2.+2.j, -2.-0.j, -2.-2.j])

In [21]:
ifft(fft(a)).round(2)

array([1.-0.j, 2.-0.j, 3.-0.j, 4.+0.j])

In [22]:
?? fft

Signature:  fft(x: numpy.ndarray[numpy.complex128]) -> numpy.ndarray[numpy.complex128]
Docstring:
Быстрое преобразование Фурье (БПФ) с использованием алгоритма Cooley-Tukey.

Параметры:
----------
x : np.ndarray[np.complex128]
    Входной массив комплексных чисел
    
Возвращает:
-----------
np.ndarray[np.complex128]
    Результат БПФ
Source:   
def fft(x: np.ndarray[np.complex128]) -> np.ndarray[np.complex128]:
    """
    Быстрое преобразование Фурье (БПФ) с использованием алгоритма Cooley-Tukey.
    
    Параметры:
    ----------
    x : np.ndarray[np.complex128]
        Входной массив комплексных чисел
        
    Возвращает:
    -----------
    np.ndarray[np.complex128]
        Результат БПФ
    """
    original_N = len(x)
    N = len(x)
    
    # Дополняем входной массив нулями до ближайшей степени двойки
    if N & (N-1) != 0:
        next_power_2 = 1 << (N - 1).bit_length()
        x = np.pad(x, (0, next_power_2 - N), mode='constant')
        N = next_power_2
    
    # Базов